language: node_js
node_js:
  - "node"
os:
  - linux
install: npm i --force
script: npm run build
branches:
  only:
    - master
deploy:
  - provider: codedeploy
    wait_until_deployed: true
    revision_type: github
    access_key_id:
      secure: "M7Z9Aqrg+VlIWkFFiQveF3MFOdKxyup5tKLz8j8DSErrzWnp3HzxxGQIMXG95syB8uO6P6s43Q7H2VxaisvPZ3FUasoIWgrKkDRcSdI2l95nulRq7cYnM17PMw5vLpn7rhfFMDPUvTSc/JBb7gFtrj/WR39y9Xr/fSL+bgW5o+aRYmdtiTzrubdRT2mGoG3Q/tjxKKdiLQZST2CcBfpzIRZn0iNa44q86fcJNpQE4rgWguy0NwVPZD62axWBrrVkPy8ubsxaY5UdiK8U5vhDnmRNsVL+3ZhTWg/+BK7caORnWg4+tXZ8X9XK7IsUwEEJZcGhzdVRV9uZ70+qDm8VfhNknx+9d9LeCJ0RJx1BW/wfej42YUTW4TjZmdKLk+I5Sa3i2tjDJ5M0kD3reSWn9MdG5wF7IU9xiAmuTK9YJZ2ciFviOlFSjH9ZBhG29oG4l9icjp8MUSvS5F6D7gJgluETRIF93+x7P4syde/KKp/5ftMNXIp9s/+Jf5C6Noa0bVFThlnlbHYiJTjb50F75MIYpEnV80f2Q4LL0X5JSQWVCFGya0BBzPFYJpDh88JFhY5FL9khZtvixgsHkcdlFV02otJSdyaOD3wDi2IVOJ4UcAmz5KNE0nvVAyuaPaqYX0SK/o3UiIJ+1YQPrebkmuJpAQyrSgKioaFVUSbyuRk="
    secret_access_key:
      secure: "FHWA3n4C5TV3BAYxljJfhlBR6Ctaty/Z2kgRPwLoxhZmw8mQ1wvHpesMe8NR8FyDzwSD2yZkX8Euzh0CZ90f18TdbZu1eZgsmG+olTkdvyWsQG3JXsXP4QDCpuVNUteAF/jfHQfLLcb/MietP12N5jcAU9P/8qcnJGLw8JbAJmH2eo05popDleLJSsOam8xuBl0JU3bOazvHT/fVkRntTvFDC0+iujCj0etKQwt3dG+KmLjnKItxkHvcM2VkoCz9BumkBzMYq5G/p69v7SLD36L4TqOrLRfdSEyj+QHQJ9zrAWmrEGTeU9VVj6DKOKu49rUzMdCQtQnK4QOLe7btPdjQlWn7icLDWX4/hppq7DQNmaS7P4p8Cudc4wAHlyLGmUam3OzFtO9Cp4SO7QIlnXCPVqvcM3ilDJKZCRcWoqX+znLgfRDgfb07RZDckGBRqELOl8AAf0i85ywTJjdeBet9S3vms5zuk4IPy1FaeH7RqrSbJguJWGNG4E6W6n17dPkiV1PHn1nYKNWmp/HdHac0k6Nr9oMYhRWuIrHTdlOttM6CMJTi6vkSrO2dFyLEUTRIdBGCCJhLITFjyfraEm3rzZCSvqOD06eHG7b+NOb7eW5LiBAl9+TMrQXzOyLjQp8ZgwTiTM1GksfLn6514vcy2piZcZd0fVD4UPOcD2c="
    application: VPIA
    file_exists_behavior: overwrite
    deployment_group: CodeDeployGitHub-DepGrp
    region: ca-central-1
    on:
      branch: master
